--- # AT - Playbook Example

- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Example of a future command with the AT module
      at: command="ls -al /var/log > /home/test/at.log" count=1 units="minutes" unique=true
