--- # From Command Line - Playbook example
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install some software
      yum: pkg={{ package }} state=latest

