--- # Pause - Playbook Example
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install httpd
      action: yum name=httpd state=installed
    - name: Pausing
      pause:
        # seconds: [amount of seconds]
        prompt: "Make sure the installation is complete... \n Enter to confirm \n crtl-c to exit"
    - name: Verify lynx installation
      action: yum name=lynx state=present
