--- # Raw - Playbook Example

- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Find the system uptime for the 'hosts' above
      raw: uptime > /home/test/uptime.log

