--- #RunOnce Playbook Example

- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts + logging it
      raw: /usr/bin/uptime >> /home/test/uptime.logging

    - name: List the /var directory and log it
      raw: ls -al /var >> /home/test/dir.list
      run_once: true
