--- # Service - Playbook Example

- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Install webserver
      yum: name=httpd state=installed
    - name: Start web server
      service: name=httpd state=started
    - name: Enable webserver
      service: name=httpd enabled=yes
