--- # WaitFor - Playbook Example

- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: Installing Apache Tomcat
      yum: name=tomcat state=installed
    - name: waiting for port 8080 to listen
      wait_for:
        port: 8080
        state: started
    - name: Verify lynx installation
      yum: name=lynx state=present
